/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseRouteImport } from './routes/case'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as CaseIndexRouteImport } from './routes/case/index'
import { Route as CaseSlugRouteImport } from './routes/case/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRoute = CaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseIndexRoute = CaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseRoute,
} as any)
const CaseSlugRoute = CaseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case': typeof CaseRouteWithChildren
  '/cases': typeof CasesRoute
  '/obrigado': typeof ObrigadoRoute
  '/case/$slug': typeof CaseSlugRoute
  '/case/': typeof CaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/obrigado': typeof ObrigadoRoute
  '/case/$slug': typeof CaseSlugRoute
  '/case': typeof CaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case': typeof CaseRouteWithChildren
  '/cases': typeof CasesRoute
  '/obrigado': typeof ObrigadoRoute
  '/case/$slug': typeof CaseSlugRoute
  '/case/': typeof CaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/case' | '/cases' | '/obrigado' | '/case/$slug' | '/case/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cases' | '/obrigado' | '/case/$slug' | '/case'
  id:
    | '__root__'
    | '/'
    | '/case'
    | '/cases'
    | '/obrigado'
    | '/case/$slug'
    | '/case/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseRoute: typeof CaseRouteWithChildren
  CasesRoute: typeof CasesRoute
  ObrigadoRoute: typeof ObrigadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case': {
      id: '/case'
      path: '/case'
      fullPath: '/case'
      preLoaderRoute: typeof CaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case/': {
      id: '/case/'
      path: '/'
      fullPath: '/case/'
      preLoaderRoute: typeof CaseIndexRouteImport
      parentRoute: typeof CaseRoute
    }
    '/case/$slug': {
      id: '/case/$slug'
      path: '/$slug'
      fullPath: '/case/$slug'
      preLoaderRoute: typeof CaseSlugRouteImport
      parentRoute: typeof CaseRoute
    }
  }
}

interface CaseRouteChildren {
  CaseSlugRoute: typeof CaseSlugRoute
  CaseIndexRoute: typeof CaseIndexRoute
}

const CaseRouteChildren: CaseRouteChildren = {
  CaseSlugRoute: CaseSlugRoute,
  CaseIndexRoute: CaseIndexRoute,
}

const CaseRouteWithChildren = CaseRoute._addFileChildren(CaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseRoute: CaseRouteWithChildren,
  CasesRoute: CasesRoute,
  ObrigadoRoute: ObrigadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
